from __future__ import annotations

from .analysis_builder import (
    ANALYSIS_BUILDER_ID,
    AGGREGATION_TITLES,
    BUILDER_VISUALIZATIONS,
    FILTER_OPERATOR_TITLES,
    SORT_DIRECTION_TITLES,
    AnalysisBuilderController,
    BuilderFilterDraft,
    BuilderVisualizationOption,
    CustomAnalysisDraft,
    builder_filter_draft_from_definition,
)
from .analysis_excel_export import (
    DashboardExcelExportError,
    DashboardExcelExportResult,
    DashboardExportCollection,
    DashboardExportCollector,
    DashboardExportIssue,
    DashboardExportItem,
    export_dashboard_excel,
    safe_unique_sheet_name,
    suggested_dashboard_excel_path,
)
from .analysis_models import (
    AnalysisCard,
    AnalysisEntity,
    CardLayoutHints,
    CardSize,
    CardType,
    ChartType,
    DashboardItem,
    ResizePolicy,
    NormalizedAnalysisData,
    VisualSettings,
)
from .analysis_data_loader import load_analysis_data
from .analysis_deadlines import (
    DeadlineDateStatus,
    DeadlineDateValue,
    build_deadline_rows,
    classify_deadline_date,
    classify_deadline_rows,
)
from .analysis_definitions import (
    AnalysisDefinition,
    AnalysisResult,
    AnalysisValidationError,
    DashboardDefinition,
    FilterDefinition,
    MeasureDefinition,
    SortDefinition,
)
from .analysis_dashboard_service import DashboardComposer, DashboardCompositionError, DashboardCompositionResult
from .analysis_dashboard_layout import (
    AddCard,
    CompactMode,
    DashboardCardPlacement,
    DashboardLayoutEngine,
    DashboardLayoutSettings,
    MoveCard,
    RemoveCard,
    ResizeCard,
)
from .analysis_dashboard_geometry import GridGeometry, PixelRect
from .analysis_dashboard_edit import (
    DashboardEditSession,
    DashboardHistoryEntry,
    HistoryOperation,
    InteractionMode,
    drag_candidate,
    logical_grid_delta,
    resize_axes,
    resize_candidate,
)
from .analysis_dashboard_workspace import (
    CUSTOM_DASHBOARD_ID,
    DashboardWorkspace,
    DashboardWorkspaceStore,
    migrate_workspace_payload,
    source_workspace_key,
)
from .analysis_custom_library import MY_ANALYSES_ID, CustomAnalysisLibraryController, SavedAnalysisListItem
from .analysis_custom_dashboard import (
    CUSTOM_ANALYSIS_DASHBOARD_SOURCE_ID,
    CustomAnalysisDashboardController,
    CustomDashboardResolutionIssue,
)
from .analysis_engine import AnalysisEngine
from .analysis_registry import AnalysisRegistry, DatasetDefinition, FieldDefinition, get_analysis_capabilities
from .analysis_renderer import analysis_result_to_card
from .analysis_repository import (
    ANALYSIS_REPOSITORY_SCHEMA_VERSION,
    AnalysisRepository,
    AnalysisRepositoryCorruptError,
    AnalysisRepositoryError,
    AnalysisRepositoryIssue,
    AnalysisRepositorySchemaError,
    FileAnalysisRepository,
    MemoryAnalysisRepository,
    default_analysis_repository_root,
)
from .analysis_service import AnalysisService, new_custom_analysis_id
from .analysis_visual_settings import (
    AnalysisVisualSettings,
    ChartVisualSettings,
    KpiVisualSettings,
    TableVisualSettings,
    CHART_PALETTES,
    PALETTE_TITLES,
    LEGEND_POSITION_TITLES,
    VISUAL_SETTINGS_OPTION_KEY,
    format_kpi_value,
    normalize_column_order,
    palette_colors,
    transform_chart_rows,
)
from .analysis_metrics import compute_metrics
from .analysis_cards import (
    build_dashboard_items,
    get_builtin_analysis_for_prepared_card,
    get_builtin_analysis_id_for_prepared_card,
)

__all__ = [
    "DashboardExcelExportError",
    "DashboardExcelExportResult",
    "DashboardExportCollection",
    "DashboardExportCollector",
    "DashboardExportIssue",
    "DashboardExportItem",
    "export_dashboard_excel",
    "safe_unique_sheet_name",
    "suggested_dashboard_excel_path",
    "ANALYSIS_BUILDER_ID",
    "AGGREGATION_TITLES",
    "BUILDER_VISUALIZATIONS",
    "FILTER_OPERATOR_TITLES",
    "SORT_DIRECTION_TITLES",
    "AnalysisBuilderController",
    "BuilderFilterDraft",
    "BuilderVisualizationOption",
    "CustomAnalysisDraft",
    "builder_filter_draft_from_definition",
    "AnalysisCard",
    "AnalysisEntity",
    "CardLayoutHints",
    "CardSize",
    "CardType",
    "ChartType",
    "DashboardItem",
    "ResizePolicy",
    "NormalizedAnalysisData",
    "VisualSettings",
    "load_analysis_data",
    "DeadlineDateStatus",
    "DeadlineDateValue",
    "build_deadline_rows",
    "classify_deadline_date",
    "classify_deadline_rows",
    "get_builtin_analysis_for_prepared_card",
    "get_builtin_analysis_id_for_prepared_card",
    "compute_metrics",
    "build_dashboard_items",
    "AnalysisDefinition",
    "AnalysisResult",
    "AnalysisValidationError",
    "DashboardDefinition",
    "DashboardComposer",
    "DashboardCompositionError",
    "DashboardCompositionResult",
    "CUSTOM_DASHBOARD_ID",
    "AddCard",
    "CompactMode",
    "DashboardCardPlacement",
    "DashboardLayoutEngine",
    "DashboardLayoutSettings",
    "MoveCard",
    "RemoveCard",
    "ResizeCard",
    "GridGeometry",
    "PixelRect",
    "DashboardEditSession",
    "DashboardHistoryEntry",
    "HistoryOperation",
    "InteractionMode",
    "drag_candidate",
    "logical_grid_delta",
    "resize_axes",
    "resize_candidate",
    "DashboardWorkspace",
    "DashboardWorkspaceStore",
    "migrate_workspace_payload",
    "source_workspace_key",
    "FilterDefinition",
    "MeasureDefinition",
    "SortDefinition",
    "MY_ANALYSES_ID",
    "CustomAnalysisLibraryController",
    "SavedAnalysisListItem",
    "CUSTOM_ANALYSIS_DASHBOARD_SOURCE_ID",
    "CustomAnalysisDashboardController",
    "CustomDashboardResolutionIssue",
    "AnalysisEngine",
    "AnalysisRegistry",
    "DatasetDefinition",
    "FieldDefinition",
    "get_analysis_capabilities",
    "analysis_result_to_card",
    "ANALYSIS_REPOSITORY_SCHEMA_VERSION",
    "AnalysisRepository",
    "AnalysisRepositoryCorruptError",
    "AnalysisRepositoryError",
    "AnalysisRepositoryIssue",
    "AnalysisRepositorySchemaError",
    "FileAnalysisRepository",
    "MemoryAnalysisRepository",
    "default_analysis_repository_root",
    "AnalysisService",
    "new_custom_analysis_id",
    "AnalysisVisualSettings",
    "ChartVisualSettings",
    "KpiVisualSettings",
    "TableVisualSettings",
    "CHART_PALETTES",
    "PALETTE_TITLES",
    "LEGEND_POSITION_TITLES",
    "VISUAL_SETTINGS_OPTION_KEY",
    "format_kpi_value",
    "normalize_column_order",
    "palette_colors",
    "transform_chart_rows",
]
